//===----------------------------------------------------------------------===//
//
// Part of the Eter Project, under the Apache License v2.0 with LLVM Exceptions.
// See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// How to compile:
// clang++ -std=c++17 -fno-objc-arc \
//     -I./metal-cpp \
//     -framework Metal -framework Foundation -framework QuartzCore \
//     ShaderJIT.cpp -o ShaderJIT

#define NS_PRIVATE_IMPLEMENTATION
#define CA_PRIVATE_IMPLEMENTATION
#define MTL_PRIVATE_IMPLEMENTATION

#include <Metal/Metal.hpp>
#include <iostream>
#include <vector>

int main() {
    // 1. Get access to the GPU (the M4 Pro chip)
    // The device represents the physical silicon and its unified memory pool
    MTL::Device* device = MTL::CreateSystemDefaultDevice();
    
    if (!device) {
        std::cerr << "Metal is not supported on this system." << std::endl;
        return -1;
    }

    std::cout << "JIT Engine: Using GPU " << device->name()->utf8String() << std::endl;

    // 2. The Shader (GPU Code written in Metal Shading Language)
    // In a real JIT scenario, this string would be generated by your compiler's backend
    const char* shaderSrc = R"(
        #include <metal_stdlib>
        using namespace metal;

        // Kernel function for parallel computation
        // 'device' address space ensures we access the shared RAM directly
        kernel void sum_arrays(device const float* in [[ buffer(0) ]],
                              device float* out [[ buffer(1) ]],
                              uint id [[ thread_position_in_grid ]]) {
            // Processing logic: multiply input by 2.0
            out[id] = in[id] * 2.0f; 
        }
    )";

    // 3. Runtime Compilation (JIT)
    // Metal-cpp converts the source string into an executable library at runtime
    NS::Error* error = nullptr;
    MTL::Library* lib = device->newLibrary(NS::String::string(shaderSrc, NS::UTF8StringEncoding), nullptr, &error);
    
    if (!lib) {
        std::cerr << "JIT Compilation error: " << error->localizedDescription()->utf8String() << std::endl;
        return -1;
    }

    // Identify the entry point for the kernel
    MTL::Function* func = lib->newFunction(NS::String::string("sum_arrays", NS::UTF8StringEncoding));
    
    // 4. Create the Pipeline State Object (PSO)
    // This step compiles the function into hardware-specific machine code for M4
    MTL::ComputePipelineState* pso = device->newComputePipelineState(func, &error);

    // 5. Data Preparation (Unified Memory)
    // M4 Pro allows zero-copy: CPU writes and GPU reads from the same physical RAM
    const int count = 1000;
    size_t size = count * sizeof(float);
    
    MTL::Buffer* bufferIn = device->newBuffer(size, MTL::ResourceStorageModeShared);
    MTL::Buffer* bufferOut = device->newBuffer(size, MTL::ResourceStorageModeShared);

    // Access the buffer contents directly via a CPU pointer
    float* inPtr = (float*)bufferIn->contents();
    for(int i = 0; i < count; i++) inPtr[i] = (float)i;

    // 6. Command Queue and Encoding
    // Prepare the list of instructions to be sent to the GPU hardware
    MTL::CommandQueue* queue = device->newCommandQueue();
    MTL::CommandBuffer* cmdBuf = queue->commandBuffer();
    MTL::ComputeCommandEncoder* encoder = cmdBuf->computeCommandEncoder();

    encoder->setComputePipelineState(pso);
    encoder->setBuffer(bufferIn, 0, 0); 
    encoder->setBuffer(bufferOut, 0, 1); 

    // 7. Dispatch Threads (Grid configuration)
    // We launch 'count' threads. M4 chips prefer thread groups of 32 or 64
    MTL::Size gridSize = MTL::Size(count, 1, 1);
    MTL::Size threadGroupSize = MTL::Size(64, 1, 1); 
    encoder->dispatchThreads(gridSize, threadGroupSize);

    // Close the recording of commands
    encoder->endEncoding();
    
    // 8. Commitment and Execution
    // Commit the commands and wait synchronously for the GPU to finish
    cmdBuf->commit();
    cmdBuf->waitUntilCompleted(); 

    // 9. Verification
    // Results are immediately available in the output buffer due to shared memory
    float* outPtr = (float*)bufferOut->contents();
    std::cout << "JIT Execution successful. Index 10: " << outPtr[10] << " (Expected 20)" << std::endl;

    // 10. Manual Memory Management (Reference Counting)
    // Since we are using Metal-cpp, we must manually release all objects
    bufferIn->release(); 
    bufferOut->release();
    pso->release(); 
    func->release(); 
    lib->release();
    queue->release(); 
    device->release();

    return 0;
}