name: Ubuntu x86

on:
  push:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { compiler: GNU, CC: gcc, CXX: g++ }
          - { compiler: LLVM, CC: clang-22, CXX: clang++-22 }
        type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          wget -O /tmp/llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo gpg --dearmor -o /usr/share/keyrings/llvm-snapshot.gpg /tmp/llvm-snapshot.gpg.key
          echo "deb [signed-by=/usr/share/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main" | sudo tee /etc/apt/sources.list.d/llvm-22.list
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install -y llvm-22 llvm-22-dev llvm-22-tools clang-22 libmlir-22-dev mlir-22-tools
          sudo apt-get install -y ninja-build
          sudo apt-get install -y python3-setuptools
          sudo pip3 install lit --break-system-packages
      - name: Build eter
        env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DCMAKE_PREFIX_PATH="/usr/lib/llvm-22/" \
                -DCMAKE_BUILD_TYPE=${{ matrix.type }} \
                -G Ninja ../
          ninja -j2
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/build
          lit -va ./test/
